// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:26ad6a2c-7fbb-4e4f-a560-5792949b56b0",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_GmJIn7Ft2",
    "aws_user_pools_web_client_id": "6hguo8mv9kjqvrb5rl99gf81it",
    "aws_content_delivery_bucket": "try15-20181019121831--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://try15-20181019121831--hostingbucket.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
